variable "do_token" {}
variable "server_name" {}
variable "region" {}
variable "size" {}
variable "image" {}
variable "ssh_fp" {}
variable "priv_key_path" {}
variable "username" {}
variable "port" {}
